name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  Build-and-push:
    runs-on: self-hosted
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker Hub Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GitHub Login
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        tags: |
         peanutsguy/spigot:latest
         ghcr.io/peanutsguy/spigot:latest
